version: "3.8"

services:
  db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  php:
    container_name: php
    build:
      context: ./php
      args:
        GIT_USEREMAIL: ${GIT_USEREMAIL}
        GIT_USERNAME: ${GIT_USERNAME}
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/docker_sf
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./app:/var/www/docker_sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: nette
    ports:
      - "${ADMINER_PORT}:8080"
    restart: always

  maildev:
    container_name: maildev
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "${MAILDEV_PORT}:80"
    restart: always

volumes:
  db_data:
  pgadmin-data:
